import { useEffect, useMemo, useState } from "react";
import "@/App.css";
import axios from "axios";
import { Bell, ChevronDown, CircleHelp, FileText, Inbox, LayoutDashboard, Menu, Search, Settings2, ShieldCheck, Sparkles, Users, X, Check, Clock3, AlertTriangle, ArrowUpRight, Download, SlidersHorizontal, UserPlus, ExternalLink } from "lucide-react";

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const API = `${BACKEND_URL}/api`;

const Home = () => {
  const [data, setData] = useState(null);
  const [selected, setSelected] = useState(null);
  const [filter, setFilter] = useState("All items");
  const [mobileNav, setMobileNav] = useState(false);
  const [activeView, setActiveView] = useState("docket");
  const [search, setSearch] = useState("");
  const [notice, setNotice] = useState("");
  useEffect(() => { axios.get(`${API}/dashboard`).then(({data: result}) => { setData(result); setSelected(result.docket[0]); }); }, []);
  const visible = useMemo(() => data?.docket.filter(item => (filter === "All items" || item.priority === filter.toLowerCase() || item.status === filter) && `${item.subject} ${item.sender} ${item.project}`.toLowerCase().includes(search.toLowerCase())) || [], [data, filter, search]);
  const updateStatus = async (status) => { if (!selected) return; try { const {data: updated} = await axios.patch(`${API}/docket/${selected.id}`, {status}); setSelected(updated); setData(prev => ({...prev, docket: prev.docket.map(item => item.id === updated.id ? updated : item)})); } catch (error) { console.error("Unable to update correspondence", error); } };
  const navigate = (view) => { setActiveView(view); setMobileNav(false); setNotice(""); };
  const notify = (message) => { setNotice(message); window.setTimeout(() => setNotice(""), 3200); };
  const exportDocket = () => { const csv = visible.map(item => `${item.subject},${item.project},${item.priority},${item.status}`).join("\n"); const blob = new Blob([`Subject,Project,Priority,Status\n${csv}`], {type: "text/csv"}); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "cleardesk-docket.csv"; link.click(); notify("Docket exported successfully"); };
  if (!data) return <div className="loading" data-testid="dashboard-loading">Loading your docket…</div>;
  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav ? "sidebar-open" : ""}`} data-testid="main-sidebar">
      <div className="brand"><div className="brand-mark">C</div><span>ClearDesk</span><button className="mobile-close" onClick={() => setMobileNav(false)} data-testid="close-mobile-nav"><X size={18}/></button></div>
      <div className="workspace-label">WORKSPACE</div><button className="workspace-switch" onClick={() => notify("Workspace switcher is ready for multiple teams")} data-testid="workspace-switch"><span className="workspace-dot"/> Meridian Group <ChevronDown size={15}/></button>
      <nav><div className="nav-label">Manage</div><NavButton active={activeView === "docket"} onClick={() => navigate("docket")} testId="nav-docket" icon={<Inbox size={18}/>} label="The Docket"><span className="nav-count">12</span></NavButton><NavButton active={activeView === "projects"} onClick={() => navigate("projects")} testId="nav-projects" icon={<LayoutDashboard size={18}/>} label="Projects"/><NavButton active={activeView === "contracts"} onClick={() => navigate("contracts")} testId="nav-contracts" icon={<FileText size={18}/>} label="Contracts"/><NavButton active={activeView === "people"} onClick={() => navigate("people")} testId="nav-people" icon={<Users size={18}/>} label="People"/><div className="nav-label second">Workspace</div><NavButton active={activeView === "settings"} onClick={() => navigate("settings")} testId="nav-settings" icon={<Settings2 size={18}/>} label="Settings"/></nav>
      <div className="sidebar-bottom"><div className="sidebar-tip"><Sparkles size={16}/><div><strong>ClearDesk demo</strong><span>Seeded workspace</span></div></div><div className="user-row"><div className="avatar">JL</div><div><strong>Jordan Lee</strong><span>Commercial Director</span></div><ChevronDown size={15}/></div></div>
    </aside>
    {mobileNav && <div className="backdrop" onClick={() => setMobileNav(false)} data-testid="mobile-nav-backdrop"/>}
    <main className="main-content"><header className="topbar"><button className="menu-button" onClick={() => setMobileNav(true)} data-testid="open-mobile-nav"><Menu size={20}/></button><div className="breadcrumb"><span>Meridian Group</span><span>/</span><strong>{activeView === "docket" ? "The Docket" : activeView[0].toUpperCase() + activeView.slice(1)}</strong></div><div className="top-actions"><button className="icon-button" onClick={() => notify("ClearDesk support is available in the demo workspace")} data-testid="help-button"><CircleHelp size={19}/></button><button className="icon-button notification" onClick={() => notify("You have 3 urgent items to review")} data-testid="notifications-button"><Bell size={19}/><i/></button><button className="top-avatar" onClick={() => navigate("settings")} data-testid="profile-button">JL</button></div></header>
      <div className="content-wrap">{notice && <div className="notice-banner" data-testid="action-notice"><Check size={16}/>{notice}</div>}{activeView !== "docket" ? <WorkspaceView view={activeView} notify={notify}/> : <><section className="page-heading"><div><div className="eyebrow">THURSDAY, 13 JUNE 2025</div><h1>Good morning, Jordan<span>.</span></h1><p>Here’s what needs your attention across the portfolio.</p></div><button className="project-picker" onClick={() => notify("Project switcher is ready for multiple active projects")} data-testid="project-picker"><span className="project-dot"/><div><small>ACTIVE PROJECT</small><strong>{data.project.name}</strong></div><ChevronDown size={16}/></button></section>
      <section className="stat-grid"><Stat icon={<Inbox/>} label="Needs review" value={data.stats.needs_review} tone="blue" detail="4 new today"/><Stat icon={<AlertTriangle/>} label="Urgent" value={data.stats.urgent} tone="red" detail="Requires action"/><Stat icon={<Clock3/>} label="Waiting on input" value={data.stats.waiting} tone="amber" detail="Across 3 projects"/><Stat icon={<LayoutDashboard/>} label="Open projects" value={data.stats.open_projects} tone="green" detail="2 updated today"/></section>
      <section className="insight-strip"><div className="insight-icon"><Sparkles size={19}/></div><div className="insight-copy"><strong>{data.insight.title}</strong><span>{data.insight.body}</span></div><div className="insight-items">{data.insight.items.map((item, i) => <div key={item} data-testid={`insight-item-${i}`}><b>0{i+1}</b>{item}</div>)}</div><button className="text-button" onClick={() => notify("Weekly insight opened in the demo workspace")} data-testid="view-insight-button">View insight <ArrowUpRight size={15}/></button></section>
      <section className="docket-section"><div className="section-heading"><div><h2>Your docket</h2><p>Priority correspondence requiring a decision or response.</p></div><button className="secondary-button" onClick={exportDocket} data-testid="export-docket-button"><Download size={15}/> Export docket</button></div><div className="toolbar"><div className="search"><Search size={17}/><input value={search} onChange={(event) => setSearch(event.target.value)} data-testid="docket-search-input" placeholder="Search correspondence"/></div><div className="filters">{["All items","Urgent","Needs review","Waiting on QS"].map(option => <button key={option} className={`filter ${filter===option ? "selected" : ""}`} onClick={() => setFilter(option)} data-testid={`filter-${option.toLowerCase().replaceAll(" ","-")}`}>{option}{option === "All items" && <span>12</span>}</button>)}</div></div><div className="docket-layout"><div className="docket-list">{visible.map(item => <DocketItem key={item.id} item={item} selected={selected?.id===item.id} onClick={() => setSelected(item)}/>)}</div>{selected && <Detail item={selected} updateStatus={updateStatus}/>}</div></section></>}</div></main>
  </div>;
};
const NavButton = ({active,onClick,testId,icon,label,children}) => <button className={`nav-item ${active ? "active" : ""}`} onClick={onClick} data-testid={testId}>{icon} {label} {children}</button>;
const WorkspaceView = ({view, notify}) => {
  const content = {
    projects: {eyebrow: "PORTFOLIO", title: "Projects", intro: "A clear view of every active commercial workspace.", icon: <LayoutDashboard/>, action: "Add project", cards: [{name: "West Quay Redevelopment", code: "WQ-042", status: "Live", meta: "NEC4 ECC Option C", value: "£48.2m"}, {name: "Harbour Point Offices", code: "HP-018", status: "Live", meta: "JCT Design & Build 2016", value: "£22.7m"}, {name: "Riverside Logistics Hub", code: "RL-031", status: "Mobilising", meta: "NEC4 ECC Option A", value: "£31.4m"}]},
    contracts: {eyebrow: "CONTRACT LIBRARY", title: "Contracts", intro: "Verified source documents across your active projects.", icon: <FileText/>, action: "Add contract", cards: [{name: "West Quay — Main Contract", code: "NEC4 ECC Option C", status: "Current", meta: "Updated 12 Jun 2025", value: "486 clauses"}, {name: "Harbour Point — MEP Subcontract", code: "JCT Design & Build 2016", status: "Current", meta: "Updated 08 Jun 2025", value: "324 clauses"}, {name: "Riverside — Enabling Works", code: "NEC4 ECC Option A", status: "Review due", meta: "Updated 28 May 2025", value: "198 clauses"}]},
    people: {eyebrow: "TEAM DIRECTORY", title: "People", intro: "The commercial and project team connected to this workspace.", icon: <Users/>, action: "Invite person", cards: [{name: "Jordan Lee", code: "Commercial Director", status: "You", meta: "All projects", value: "Admin"}, {name: "Amelia Shah", code: "Senior Quantity Surveyor", status: "Active", meta: "West Quay · Harbour Point", value: "Editor"}, {name: "Daniel Osei", code: "Project Manager", status: "Active", meta: "Riverside Logistics Hub", value: "Editor"}]},
    settings: {eyebrow: "WORKSPACE", title: "Settings", intro: "Keep your ClearDesk workspace aligned with how your team works.", icon: <Settings2/>, action: "Save changes", cards: [{name: "Docket preferences", code: "Prioritize urgent correspondence", status: "On", meta: "Deadline reminders enabled", value: "Edit"}, {name: "Review permissions", code: "Require approval before sending", status: "On", meta: "Applies to all projects", value: "Edit"}, {name: "Notifications", code: "Daily commercial digest", status: "Off", meta: "Next digest: tomorrow at 08:00", value: "Edit"}]}
  }[view];
  return <section className="workspace-view" data-testid={`${view}-view`}><div className="workspace-heading"><div><div className="eyebrow">{content.eyebrow}</div><h1>{content.title}</h1><p>{content.intro}</p></div><button className="primary-button" onClick={() => notify(`${content.action} is available from this demo workspace`)} data-testid={`${view}-primary-action`}>{view === "people" ? <UserPlus size={16}/> : view === "settings" ? <Check size={16}/> : <FileText size={16}/>} {content.action}</button></div><div className="workspace-summary"><div className="workspace-summary-icon">{content.icon}</div><div><strong>{view === "projects" ? "8 open projects" : view === "contracts" ? "8 verified documents" : view === "people" ? "14 workspace members" : "Workspace is up to date"}</strong><span>Last updated a few minutes ago</span></div><button className="icon-button" onClick={() => notify("View refreshed")} data-testid={`${view}-refresh-button`}><SlidersHorizontal size={17}/></button></div><div className="workspace-cards">{content.cards.map(card => <button className="workspace-card" key={card.name} onClick={() => notify(`${card.name} selected`)} data-testid={`${view}-card-${card.name.toLowerCase().replaceAll(" ","-")}`}><div className="card-icon">{content.icon}</div><div className="workspace-card-copy"><div className="card-top"><span>{card.status}</span><ExternalLink size={14}/></div><h3>{card.name}</h3><p>{card.code}</p><small>{card.meta}</small></div><strong className="card-value">{card.value}</strong></button>)}</div></section>;
};
const Stat = ({icon,label,value,tone,detail}) => <div className="stat-card" data-testid={`stat-${label.toLowerCase().replaceAll(" ","-")}`}><div className={`stat-icon ${tone}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></div>;
const DocketItem = ({item,selected,onClick}) => <button className={`docket-item ${selected ? "selected" : ""}`} onClick={onClick} data-testid={`docket-item-${item.id}`}><div className={`priority-line ${item.priority}`}/><div className="item-main"><div className="item-top"><span className={`tag ${item.priority}`}>{item.priority === "urgent" ? "Urgent" : item.type}</span><time>{item.received}</time></div><h3>{item.subject}</h3><p>{item.sender} <span>·</span> {item.project}</p><div className="item-bottom"><span className="status"><i className={item.status === "Waiting on QS" ? "amber" : ""}/>{item.status}</span><span className="deadline"><Clock3 size={13}/>{item.deadline}</span></div></div><ChevronDown className="item-chevron" size={17}/></button>;
const Detail = ({item,updateStatus}) => { const [detailNotice, setDetailNotice] = useState(""); const download = () => { const link = document.createElement("a"); link.href = `data:text/plain;charset=utf-8,${encodeURIComponent(`ClearDesk demo attachment\n${item.attachment}`)}`; link.download = item.attachment; link.click(); setDetailNotice("Attachment downloaded"); }; return <article className="detail-panel" data-testid="correspondence-detail"><div className="detail-top"><div><span className={`tag ${item.priority}`}>{item.priority === "urgent" ? "Urgent attention" : item.type}</span><h2>{item.subject}</h2><p className="detail-sender">From <strong>{item.sender}</strong> · {item.received}</p></div><button className="icon-button" onClick={() => setDetailNotice("More correspondence actions are available after review")} data-testid="detail-more-button"><ChevronDown size={18}/></button></div>{detailNotice && <div className="detail-notice" data-testid="detail-action-notice"><Check size={14}/>{detailNotice}</div>}<div className="risk-callout"><div className="risk-title"><ShieldCheck size={17}/> Contract check <span>{item.risk} risk</span></div><p>{item.risk_detail}</p></div><div className="detail-block"><label>Verified contract excerpt</label><blockquote>“{item.excerpt}”</blockquote><button className="link-button" onClick={() => setDetailNotice("Clause 8.4 opened in the contract viewer")} data-testid="open-contract-button">Open NEC4 ECC · Clause 8.4 <ArrowUpRight size={14}/></button></div><div className="detail-block attachment"><FileText size={20}/><div><strong>{item.attachment}</strong><span>Added with this correspondence</span></div><button className="icon-button" onClick={download} data-testid="download-attachment-button"><Download size={16}/></button></div><div className="detail-actions"><button className="primary-button" onClick={() => updateStatus("In progress")} data-testid="draft-reply-button"><Sparkles size={16}/> Draft contract-backed reply</button><button className="secondary-button" onClick={() => updateStatus("Reviewed")} data-testid="mark-reviewed-button"><Check size={16}/> Mark reviewed</button></div></article>; };

function App() {
  return (
    <Home />
  );
}

export default App;
