import { useEffect, useMemo, useState } from "react";
import "@/App.css";
import axios from "axios";
import { Bell, ChevronDown, CircleHelp, FileText, Inbox, LayoutDashboard, Menu, PanelLeft, Search, Settings2, ShieldCheck, Sparkles, Users, X, Check, Clock3, AlertTriangle, ArrowUpRight } from "lucide-react";

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const API = `${BACKEND_URL}/api`;

const Home = () => {
  const [data, setData] = useState(null);
  const [selected, setSelected] = useState(null);
  const [filter, setFilter] = useState("All items");
  const [mobileNav, setMobileNav] = useState(false);
  useEffect(() => { axios.get(`${API}/dashboard`).then(({data: result}) => { setData(result); setSelected(result.docket[0]); }); }, []);
  const visible = useMemo(() => data?.docket.filter(item => filter === "All items" || item.priority === filter.toLowerCase() || item.status === filter) || [], [data, filter]);
  const updateStatus = async (status) => { if (!selected) return; try { const {data: updated} = await axios.patch(`${API}/docket/${selected.id}`, {status}); setSelected(updated); setData(prev => ({...prev, docket: prev.docket.map(item => item.id === updated.id ? updated : item)})); } catch (error) { console.error("Unable to update correspondence", error); } };
  if (!data) return <div className="loading" data-testid="dashboard-loading">Loading your docket…</div>;
  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav ? "sidebar-open" : ""}`} data-testid="main-sidebar">
      <div className="brand"><div className="brand-mark">C</div><span>ClearDesk</span><button className="mobile-close" onClick={() => setMobileNav(false)} data-testid="close-mobile-nav"><X size={18}/></button></div>
      <div className="workspace-label">WORKSPACE</div><button className="workspace-switch" data-testid="workspace-switch"><span className="workspace-dot"/> Meridian Group <ChevronDown size={15}/></button>
      <nav><div className="nav-label">Manage</div><button className="nav-item active" data-testid="nav-docket"><Inbox size={18}/> The Docket <span className="nav-count">12</span></button><button className="nav-item" data-testid="nav-projects"><LayoutDashboard size={18}/> Projects</button><button className="nav-item" data-testid="nav-contracts"><FileText size={18}/> Contracts</button><button className="nav-item" data-testid="nav-people"><Users size={18}/> People</button><div className="nav-label second">Workspace</div><button className="nav-item" data-testid="nav-settings"><Settings2 size={18}/> Settings</button></nav>
      <div className="sidebar-bottom"><div className="sidebar-tip"><Sparkles size={16}/><div><strong>ClearDesk demo</strong><span>Seeded workspace</span></div></div><div className="user-row"><div className="avatar">JL</div><div><strong>Jordan Lee</strong><span>Commercial Director</span></div><ChevronDown size={15}/></div></div>
    </aside>
    {mobileNav && <div className="backdrop" onClick={() => setMobileNav(false)} data-testid="mobile-nav-backdrop"/>}
    <main className="main-content"><header className="topbar"><button className="menu-button" onClick={() => setMobileNav(true)} data-testid="open-mobile-nav"><Menu size={20}/></button><div className="breadcrumb"><span>Meridian Group</span><span>/</span><strong>The Docket</strong></div><div className="top-actions"><button className="icon-button" data-testid="help-button"><CircleHelp size={19}/></button><button className="icon-button notification" data-testid="notifications-button"><Bell size={19}/><i/></button><div className="top-avatar">JL</div></div></header>
      <div className="content-wrap"><section className="page-heading"><div><div className="eyebrow">THURSDAY, 13 JUNE 2025</div><h1>Good morning, Jordan<span>.</span></h1><p>Here’s what needs your attention across the portfolio.</p></div><button className="project-picker" data-testid="project-picker"><span className="project-dot"/><div><small>ACTIVE PROJECT</small><strong>{data.project.name}</strong></div><ChevronDown size={16}/></button></section>
      <section className="stat-grid"><Stat icon={<Inbox/>} label="Needs review" value={data.stats.needs_review} tone="blue" detail="4 new today"/><Stat icon={<AlertTriangle/>} label="Urgent" value={data.stats.urgent} tone="red" detail="Requires action"/><Stat icon={<Clock3/>} label="Waiting on input" value={data.stats.waiting} tone="amber" detail="Across 3 projects"/><Stat icon={<LayoutDashboard/>} label="Open projects" value={data.stats.open_projects} tone="green" detail="2 updated today"/></section>
      <section className="insight-strip"><div className="insight-icon"><Sparkles size={19}/></div><div className="insight-copy"><strong>{data.insight.title}</strong><span>{data.insight.body}</span></div><div className="insight-items">{data.insight.items.map((item, i) => <div key={item} data-testid={`insight-item-${i}`}><b>0{i+1}</b>{item}</div>)}</div><button className="text-button" data-testid="view-insight-button">View insight <ArrowUpRight size={15}/></button></section>
      <section className="docket-section"><div className="section-heading"><div><h2>Your docket</h2><p>Priority correspondence requiring a decision or response.</p></div><button className="secondary-button" data-testid="export-docket-button">Export docket <ArrowUpRight size={15}/></button></div><div className="toolbar"><div className="search"><Search size={17}/><input data-testid="docket-search-input" placeholder="Search correspondence"/></div><div className="filters">{["All items","Urgent","Needs review","Waiting on QS"].map(option => <button key={option} className={`filter ${filter===option ? "selected" : ""}`} onClick={() => setFilter(option)} data-testid={`filter-${option.toLowerCase().replaceAll(" ","-")}`}>{option}{option === "All items" && <span>12</span>}</button>)}</div></div><div className="docket-layout"><div className="docket-list">{visible.map(item => <DocketItem key={item.id} item={item} selected={selected?.id===item.id} onClick={() => setSelected(item)}/>)}</div>{selected && <Detail item={selected} updateStatus={updateStatus}/>}</div></section></div></main>
  </div>;
};
const Stat = ({icon,label,value,tone,detail}) => <div className="stat-card" data-testid={`stat-${label.toLowerCase().replaceAll(" ","-")}`}><div className={`stat-icon ${tone}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></div>;
const DocketItem = ({item,selected,onClick}) => <button className={`docket-item ${selected ? "selected" : ""}`} onClick={onClick} data-testid={`docket-item-${item.id}`}><div className={`priority-line ${item.priority}`}/><div className="item-main"><div className="item-top"><span className={`tag ${item.priority}`}>{item.priority === "urgent" ? "Urgent" : item.type}</span><time>{item.received}</time></div><h3>{item.subject}</h3><p>{item.sender} <span>·</span> {item.project}</p><div className="item-bottom"><span className="status"><i className={item.status === "Waiting on QS" ? "amber" : ""}/>{item.status}</span><span className="deadline"><Clock3 size={13}/>{item.deadline}</span></div></div><ChevronDown className="item-chevron" size={17}/></button>;
const Detail = ({item,updateStatus}) => <article className="detail-panel" data-testid="correspondence-detail"><div className="detail-top"><div><span className={`tag ${item.priority}`}>{item.priority === "urgent" ? "Urgent attention" : item.type}</span><h2>{item.subject}</h2><p className="detail-sender">From <strong>{item.sender}</strong> · {item.received}</p></div><button className="icon-button" data-testid="detail-more-button"><ChevronDown size={18}/></button></div><div className="risk-callout"><div className="risk-title"><ShieldCheck size={17}/> Contract check <span>{item.risk} risk</span></div><p>{item.risk_detail}</p></div><div className="detail-block"><label>Verified contract excerpt</label><blockquote>“{item.excerpt}”</blockquote><button className="link-button" data-testid="open-contract-button">Open NEC4 ECC · Clause 8.4 <ArrowUpRight size={14}/></button></div><div className="detail-block attachment"><FileText size={20}/><div><strong>{item.attachment}</strong><span>Added with this correspondence</span></div><button className="icon-button" data-testid="download-attachment-button"><ArrowUpRight size={16}/></button></div><div className="detail-actions"><button className="primary-button" onClick={() => updateStatus("In progress")} data-testid="draft-reply-button"><Sparkles size={16}/> Draft contract-backed reply</button><button className="secondary-button" onClick={() => updateStatus("Reviewed")} data-testid="mark-reviewed-button"><Check size={16}/> Mark reviewed</button></div></article>;

function App() {
  return (
    <Home />
  );
}

export default App;
